name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/cgwalters/fcos-buildroot

    steps:
    - name: Install skopeo
      run: yum -y install skopeo
    - uses: actions/checkout@v2
    - name: Hack in updated ostree
      run: rpm -Uvh https://kojipkgs.fedoraproject.org//packages/ostree/2021.2/2.fc33/x86_64/ostree-{,devel-,libs-}2021.2-2.fc33.x86_64.rpm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
